# Site settings
title:       Sergio Rykov
email:       Sergio.On.Social@gmail.com
author:      Sergio Rykov
description: "Thougts on tech, development, life hacks, being a father"
baseurl:     ""
url:         "http://sergiorykov.github.io"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: sergiorykovblog

# Social icons
github_username: sergiorykov
bitbucket_username:
stackoverflow_id: 323979
twitter_username: wilyrussian
google_plus_id: Sergio.On.Social@gmail.com
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
  
kramdown:
  input: GFM
