# Site settings
# DOCUMENTATION https://jekyllrb.com/docs/configuration/
title:       Sergio Rykov
email:       Sergio.Rykov@gmail.com
author:      Sergio Rykov
description: "Thougts on tech, development, life hacks, being a father"
baseurl:     ""

url:         "https://sergiorykov.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false

fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)

disqus_shortname: sergiorykovblog

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: sergiorykov
bitbucket_username:
stackoverflow_id: 323979
twitter_username: wilyrussian
google_plus_id: 
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons

share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings

markdown:     kramdown
highlighter: rouge
permalink:    pretty
paginate:     4
sass:
  style: compressed
kramdown: 
  auto_ids: true 
  input: GFM 
  toc_levels: 1..6 
  smart_quotes: lsquo,rsquo,ldquo,rdquo 
  enable_coderay: false 

  # https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

# http://jekyllrb.com/docs/permalinks/
# http://joshualande.com/short-urls-jekyll/
permalink: "/:title"

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap